### PR TITLE
build: use default root base url

### PR DESCRIPTION
**Pull request by xseman**
Set URL to default as per old documentation.

Actual one https://tsoa-community.github.io/ doesn't redirect to the `/docs`, you'll get 404.

image

### CODE REVIEW

**Comment by WoH** [comment]
But wouldn't this interfere with https://tsoa-community.github.io/reference/?

**Comment by xseman** [comment]
My bad, I got confused by the `/docs/` configuration because the repository used to be accessible from the root page, now it's accessible from the page `https://<username>.github.io/<repository>`. You can ignore this PR.

My suggestion is to create a `tsoa-community` repository which points to https://tsoa-community.github.io/.
This repository can include simple lists to reference other subpages such as `/docs` and `/reference`.

**Comment by xseman** [comment]
Never mind, I thought this approach would work, but it didn't. I tested if using the organization name as the repository would resolve to the root of the URL, but unfortunately, it still uses subdirectory.

**Comment by xseman** [comment]
I discovered that it is indeed possible to obtain the root page, it repository should be named `tsoa-community.github.io`. Would you be interested in having main page like this? I'd be happy to assist you.

**Pull request closed without merging**
